//! Deterministic Jarvis checkpoints emitted around tools and PTY operations.
//!
//! These events drive the ephemeral collapsed-widget status and the small
//! expanded timeline. They are NEVER generated by the model and never stored:
//! the frontend keeps a bounded view and prunes completed events.

use serde::Serialize;
use tauri::{AppHandle, Emitter};

pub const JARVIS_ACTIVITY_EVENT: &str = "jarvis://activity";

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum JarvisActivityStatus {
    Running,
    Done,
    Failed,
    WaitingConfirmation,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct JarvisActivityEvent {
    pub request_id: String,
    pub workspace_id: String,
    pub phase: String,
    pub label: String,
    pub status: JarvisActivityStatus,
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_session_id: Option<String>,
}

pub fn emit_checkpoint(
    app: &AppHandle,
    request_id: &str,
    workspace_id: &str,
    phase: &str,
    label: &str,
    status: JarvisActivityStatus,
    target_session_id: Option<String>,
) {
    let _ = app.emit(
        JARVIS_ACTIVITY_EVENT,
        JarvisActivityEvent {
            request_id: request_id.to_string(),
            workspace_id: workspace_id.to_string(),
            phase: phase.to_string(),
            label: label.to_string(),
            status,
            created_at: chrono::Utc::now().to_rfc3339(),
            target_session_id,
        },
    );
}
