use crate::terminal_engine::frame::CursorPosition;
use vt100::Parser;

/// Max scrollback rows kept per session for workspace remount rehydrate.
/// Matches xterm.js scrollback so frontend/backend stay aligned.
pub const SCROLLBACK_LINES: usize = 1000;

pub struct AnsiParser {
    parser: Parser,
    /// Separate bounded history view. It can be reset at a screen-clear
    /// barrier without losing the live parser's cursor/mode state.
    history_parser: Parser,
    cols: u16,
    rows: u16,
    focus_reporting: bool,
    focus_sequence: Vec<u8>,
    history_escape: Vec<u8>,
}

impl AnsiParser {
    pub fn new(cols: u16, rows: u16) -> Self {
        Self {
            parser: Parser::new(rows, cols, SCROLLBACK_LINES),
            history_parser: Parser::new(rows, cols, SCROLLBACK_LINES),
            cols,
            rows,
            focus_reporting: false,
            focus_sequence: Vec::new(),
            history_escape: Vec::new(),
        }
    }

    pub fn process(&mut self, data: &[u8]) {
        self.track_focus_reporting(data);
        self.parser.process(data);
        self.process_history(data);
    }

    /// Resize the terminal without wiping scrollback history.
    /// Uses vt100 `set_size` instead of recreating the parser.
    pub fn resize(&mut self, cols: u16, rows: u16) {
        if cols == 0 || rows == 0 {
            return;
        }
        if self.cols == cols && self.rows == rows {
            return;
        }
        self.parser.set_size(rows, cols);
        self.history_parser.set_size(rows, cols);
        self.cols = cols;
        self.rows = rows;
        // Pin view to the live screen (offset 0).
        self.parser.set_scrollback(0);
    }

    pub fn screen(&self) -> &vt100::Screen {
        self.parser.screen()
    }

    /// Return the bounded scrollback history as a terminal-formatted stream.
    ///
    /// xterm is disposed when a workspace is switched, so the frontend needs
    /// the parser's history to rebuild the buffer on the next mount. The
    /// parser is always returned to its live viewport before this method
    /// returns; the viewport itself belongs to xterm/frontend state.
    pub fn scrollback_text_for_rehydrate(&mut self) -> Vec<u8> {
        Self::rehydrate_text_inner(&mut self.history_parser, self.rows, self.cols).into_bytes()
    }

    /// Return a parser-generated byte stream that reconstructs the visible
    /// terminal state in another terminal parser.
    ///
    /// `rows_formatted()` requires the caller to position the cursor before
    /// every row and does not include the final cursor position or input
    /// modes. `state_formatted()` handles cursor movement, attributes, cursor
    /// visibility, mouse modes, bracketed paste, keypad/cursor modes, and the
    /// title as one ordered stream. Focus reporting is tracked separately
    /// because vt100 does not expose it as an input mode.
    pub fn state_for_rehydrate(&mut self) -> Vec<u8> {
        let result = {
            self.parser.set_scrollback(0);
            let screen = self.parser.screen();
            let mut state = Vec::new();
            if screen.alternate_screen() {
                state.extend_from_slice(b"\x1b[?1049h");
            } else {
                state.extend_from_slice(b"\x1b[?1049l");
            }
            state.extend(screen.state_formatted());
            state.extend_from_slice(if self.focus_reporting {
                b"\x1b[?1004h"
            } else {
                b"\x1b[?1004l"
            });
            state
        };
        self.parser.set_scrollback(0);
        result
    }

    /// Track the one DEC private mode that vt100 does not expose while
    /// retaining partial escape sequences across ConPTY read boundaries.
    fn track_focus_reporting(&mut self, data: &[u8]) {
        for &byte in data {
            if self.focus_sequence.is_empty() {
                if byte == 0x1b {
                    self.focus_sequence.push(byte);
                }
                continue;
            }

            if byte == 0x1b {
                self.focus_sequence.clear();
                self.focus_sequence.push(byte);
                continue;
            }

            self.focus_sequence.push(byte);
            if self.focus_sequence.len() > 64 {
                self.focus_sequence.clear();
                continue;
            }

            if self.focus_sequence.len() == 2 && byte != b'[' {
                self.focus_sequence.clear();
                continue;
            }

            if self.focus_sequence.len() >= 3 && (0x40..=0x7e).contains(&byte) {
                let sequence = &self.focus_sequence;
                if sequence.len() >= 4
                    && sequence[0] == 0x1b
                    && sequence[1] == b'['
                    && sequence[2..sequence.len() - 1] == *b"?1004"
                {
                    self.focus_reporting = byte == b'h';
                }
                self.focus_sequence.clear();
            }
        }
    }

    /// Recover scrollback plus the current visible screen for xterm
    /// rehydrate. vt100's public `visible_rows()` assumes the viewport height
    /// is at least the scrollback offset, so temporarily expand the history
    /// parser's row count to expose the complete bounded history in one view.
    fn rehydrate_text_inner(parser: &mut Parser, rows: u16, cols: u16) -> String {
        parser.set_scrollback(usize::MAX);
        let max_offset = parser.screen().scrollback().min(SCROLLBACK_LINES);
        let cap = SCROLLBACK_LINES.saturating_add(rows as usize);
        let expanded_rows = rows.saturating_add(max_offset as u16);
        parser.set_size(expanded_rows, cols);
        parser.set_scrollback(max_offset);
        let lines: Vec<String> = parser
            .screen()
            .rows_formatted(0, cols)
            .map(|line| String::from_utf8_lossy(&line).into_owned())
            .collect();

        // Restore the real PTY geometry and live viewport before returning.
        parser.set_size(rows, cols);
        parser.set_scrollback(0);

        let start = lines.len().saturating_sub(cap);
        let selected = &lines[start..];
        let mut end = selected.len();
        while end > 0 && strip_ansi(&selected[end - 1]).trim_end().is_empty() {
            end -= 1;
        }
        if end == 0 {
            return String::new();
        }

        let mut out = String::with_capacity(end * (cols as usize / 2 + 2));
        for (index, line) in selected[..end].iter().enumerate() {
            if index > 0 {
                out.push('\r');
                out.push('\n');
            }
            out.push_str(line);
        }
        out
    }

    /// Feed the history parser while treating a full-screen clear as a
    /// boundary. The live parser still receives the original uninterrupted
    /// stream above, so cursor, modes, alternate screen, and title state are
    /// never reconstructed from this intentionally lightweight history view.
    fn process_history(&mut self, data: &[u8]) {
        let mut plain = Vec::with_capacity(data.len());

        for &byte in data {
            if self.history_escape.is_empty() {
                if byte == 0x1b {
                    if !plain.is_empty() {
                        self.history_parser.process(&plain);
                        plain.clear();
                    }
                    self.history_escape.push(byte);
                } else {
                    plain.push(byte);
                }
                continue;
            }

            self.history_escape.push(byte);
            if self.history_escape.len() == 2 && byte != b'[' {
                plain.extend_from_slice(&self.history_escape);
                self.history_escape.clear();
                continue;
            }

            let is_csi_final = self.history_escape.len() >= 3 && (0x40..=0x7e).contains(&byte);
            if !is_csi_final && self.history_escape.len() <= 64 {
                continue;
            }

            let sequence = std::mem::take(&mut self.history_escape);
            if is_clear_screen_sequence(&sequence) {
                self.history_parser = Parser::new(self.rows, self.cols, SCROLLBACK_LINES);
            }
            self.history_parser.process(&sequence);
        }

        if !plain.is_empty() {
            self.history_parser.process(&plain);
        }
    }

    /// Visible screen only (no scrollback) — lightweight helper.
    #[allow(dead_code)]
    pub fn screen_text(&self, rows: u16, cols: u16) -> String {
        let screen = self.parser.screen();
        let mut out = String::with_capacity((rows as usize + 1) * (cols as usize + 1));
        for r in 0..rows {
            let mut line = String::with_capacity(cols as usize);
            for c in 0..cols {
                if let Some(cell) = screen.cell(r, c) {
                    let ch = cell.contents().chars().next().unwrap_or(' ');
                    line.push(ch);
                } else {
                    line.push(' ');
                }
            }
            let trimmed = line.trim_end();
            out.push_str(trimmed);
            if r + 1 < rows {
                out.push('\r');
                out.push('\n');
            }
        }
        out
    }

    #[allow(dead_code)]
    pub fn cursor_position(&self) -> CursorPosition {
        let (row, col) = self.parser.screen().cursor_position();
        CursorPosition { row, col }
    }

    #[allow(dead_code)]
    pub fn window_title(&self) -> Option<String> {
        let title = self.parser.screen().title();
        if title.is_empty() {
            None
        } else {
            Some(title.to_string())
        }
    }
}

fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\x1b' && chars.next() == Some('[') {
            for c in chars.by_ref() {
                if c >= '\x40' && c <= '\x7E' {
                    break;
                }
            }
        } else if c != '\x1b' {
            out.push(c);
        }
    }
    out
}

fn is_clear_screen_sequence(sequence: &[u8]) -> bool {
    if sequence == b"\x1bc" {
        return true;
    }
    if sequence.len() < 4
        || sequence[0] != 0x1b
        || sequence[1] != b'['
        || *sequence.last().unwrap_or(&0) != b'J'
    {
        return false;
    }

    sequence[2..sequence.len() - 1]
        .split(|byte| *byte == b';')
        .any(|parameter| parameter == b"2" || parameter == b"3")
}

#[cfg(test)]
mod tests {
    use super::AnsiParser;

    #[test]
    fn state_rehydrate_preserves_screen_modes_and_cursor_state() {
        let mut parser = AnsiParser::new(20, 5);
        parser.process(b"\x1b[?1049h\x1b[?1003h\x1b[?1006h\x1b[?1004h\x1b[?2004h\x1b[3;5Hhello");

        let state = parser.state_for_rehydrate();
        let state = String::from_utf8(state).expect("formatted vt100 state is UTF-8");

        assert!(state.contains("\x1b[?1049h"));
        assert!(state.contains("\x1b[?1003h"));
        assert!(state.contains("\x1b[?1006h"));
        assert!(state.contains("\x1b[?1004h"));
        assert!(state.contains("\x1b[?2004h"));
        assert!(state.contains("hello"));

        let mut replayed = vt100::Parser::new(5, 20, 1000);
        replayed.process(state.as_bytes());
        assert_eq!(replayed.screen().cursor_position(), (2, 9));
        assert_eq!(replayed.screen().cell(2, 4).unwrap().contents(), "h");

        let mut split = AnsiParser::new(20, 5);
        split.process(b"\x1b[?10");
        split.process(b"04h");
        assert!(String::from_utf8(split.state_for_rehydrate())
            .expect("formatted vt100 state is UTF-8")
            .contains("\x1b[?1004h"));
    }

    #[test]
    fn scrollback_rehydrate_includes_history_and_returns_to_live_view() {
        let mut parser = AnsiParser::new(20, 3);
        for index in 0..50 {
            let line = format!("line-{index}\r\n");
            parser.process(line.as_bytes());
        }

        let history = String::from_utf8(parser.scrollback_text_for_rehydrate())
            .expect("formatted scrollback is UTF-8");

        assert!(
            history.contains("line-0"),
            "history was not rehydrated: {history:?}"
        );
        assert!(
            history.contains("line-49"),
            "live screen was not rehydrated: {history:?}"
        );
        assert_eq!(parser.screen().scrollback(), 0);
        assert_eq!(parser.screen().size(), (3, 20));
    }

    #[test]
    fn clear_screen_starts_a_new_rehydrate_history() {
        let mut parser = AnsiParser::new(20, 3);
        parser.process(b"old-one\r\nold-two\r\nold-three\r\n");
        // ConPTY can split an ANSI sequence across reader chunks.
        parser.process(b"\x1b[");
        parser.process(b"2J\x1b[Hnew-screen");

        let history = String::from_utf8(parser.scrollback_text_for_rehydrate())
            .expect("formatted scrollback is UTF-8");

        assert!(
            !history.contains("old-one"),
            "cleared history leaked: {history:?}"
        );
        assert!(
            history.contains("new-screen"),
            "post-clear screen missing: {history:?}"
        );
    }
}
