use crate::terminal_engine::frame::CursorPosition;
use vt100::Parser;

/// Max scrollback rows kept per session for workspace remount rehydrate.
/// Matches xterm.js scrollback so frontend/backend stay aligned.
pub const SCROLLBACK_LINES: usize = 1000;

pub struct AnsiParser {
    parser: Parser,
    cols: u16,
    rows: u16,
    focus_reporting: bool,
    focus_sequence: Vec<u8>,
}

impl AnsiParser {
    pub fn new(cols: u16, rows: u16) -> Self {
        Self {
            parser: Parser::new(rows, cols, SCROLLBACK_LINES),
            cols,
            rows,
            focus_reporting: false,
            focus_sequence: Vec::new(),
        }
    }

    pub fn process(&mut self, data: &[u8]) {
        self.track_focus_reporting(data);
        self.parser.process(data);
    }

    /// Resize the terminal without wiping scrollback history.
    /// Uses vt100 `set_size` instead of recreating the parser.
    pub fn resize(&mut self, cols: u16, rows: u16) {
        if cols == 0 || rows == 0 {
            return;
        }
        if self.cols == cols && self.rows == rows {
            return;
        }
        self.parser.set_size(rows, cols);
        self.cols = cols;
        self.rows = rows;
        // Pin view to the live screen (offset 0).
        self.parser.set_scrollback(0);
    }

    pub fn screen(&self) -> &vt100::Screen {
        self.parser.screen()
    }

    /// Visible screen only, formatted for xterm rehydrate.
    ///
    /// Important: this deliberately excludes scrollback history. Including
    /// scrollback caused the bug where a cleared terminal repopulated old
    /// output after a workspace remount. Only the current live screen is
    /// returned so the frontend sees exactly what the user last saw.
    pub fn screen_text_for_rehydrate(&mut self) -> String {
        // Always restore live viewport offset, even on early return / panic paths.
        let result = self.screen_text_for_rehydrate_inner();
        self.parser.set_scrollback(0);
        result
    }

    /// Return a parser-generated byte stream that reconstructs the visible
    /// terminal state in another terminal parser.
    ///
    /// `rows_formatted()` requires the caller to position the cursor before
    /// every row and does not include the final cursor position or input
    /// modes. `state_formatted()` handles cursor movement, attributes, cursor
    /// visibility, mouse modes, bracketed paste, keypad/cursor modes, and the
    /// title as one ordered stream. Focus reporting is tracked separately
    /// because vt100 does not expose it as an input mode.
    pub fn state_for_rehydrate(&mut self) -> Vec<u8> {
        let result = {
            self.parser.set_scrollback(0);
            let screen = self.parser.screen();
            let mut state = Vec::new();
            if screen.alternate_screen() {
                state.extend_from_slice(b"\x1b[?1049h");
            } else {
                state.extend_from_slice(b"\x1b[?1049l");
            }
            state.extend(screen.state_formatted());
            state.extend_from_slice(if self.focus_reporting {
                b"\x1b[?1004h"
            } else {
                b"\x1b[?1004l"
            });
            state
        };
        self.parser.set_scrollback(0);
        result
    }

    /// Track the one DEC private mode that vt100 does not expose while
    /// retaining partial escape sequences across ConPTY read boundaries.
    fn track_focus_reporting(&mut self, data: &[u8]) {
        for &byte in data {
            if self.focus_sequence.is_empty() {
                if byte == 0x1b {
                    self.focus_sequence.push(byte);
                }
                continue;
            }

            if byte == 0x1b {
                self.focus_sequence.clear();
                self.focus_sequence.push(byte);
                continue;
            }

            self.focus_sequence.push(byte);
            if self.focus_sequence.len() > 64 {
                self.focus_sequence.clear();
                continue;
            }

            if self.focus_sequence.len() == 2 && byte != b'[' {
                self.focus_sequence.clear();
                continue;
            }

            if self.focus_sequence.len() >= 3 && (0x40..=0x7e).contains(&byte) {
                let sequence = &self.focus_sequence;
                if sequence.len() >= 4
                    && sequence[0] == 0x1b
                    && sequence[1] == b'['
                    && sequence[2..sequence.len() - 1] == *b"?1004"
                {
                    self.focus_reporting = byte == b'h';
                }
                self.focus_sequence.clear();
            }
        }
    }

    // Recover only the current visible screen for xterm rehydrate.
    //
    // We intentionally do NOT include the VT100 scrollback history here.
    // Including scrollback caused the bug where a cleared terminal (e.g.
    // `clear` in PowerShell) would still show old output after switching
    // workspaces, because the scrollback kept the old lines while the live
    // screen was empty. Returning only the live screen preserves the
    // cleared state on remount.
    fn screen_text_for_rehydrate_inner(&mut self) -> String {
        self.parser.set_scrollback(0);
        let cols = self.cols;
        let mut lines: Vec<String> = Vec::with_capacity(self.rows as usize);

        for line in self.parser.screen().rows_formatted(0, cols) {
            lines.push(String::from_utf8_lossy(&line).into_owned());
        }

        let mut end = lines.len();
        while end > 0 && strip_ansi(&lines[end - 1]).trim_end().is_empty() {
            end -= 1;
        }
        if end == 0 {
            return String::new();
        }

        let mut out = String::with_capacity(end * (cols as usize / 2 + 2));
        for (i, line) in lines[..end].iter().enumerate() {
            if i > 0 {
                out.push('\r');
                out.push('\n');
            }
            out.push_str(line);
        }
        out
    }

    /// Visible screen only (no scrollback) — lightweight helper.
    #[allow(dead_code)]
    pub fn screen_text(&self, rows: u16, cols: u16) -> String {
        let screen = self.parser.screen();
        let mut out = String::with_capacity((rows as usize + 1) * (cols as usize + 1));
        for r in 0..rows {
            let mut line = String::with_capacity(cols as usize);
            for c in 0..cols {
                if let Some(cell) = screen.cell(r, c) {
                    let ch = cell.contents().chars().next().unwrap_or(' ');
                    line.push(ch);
                } else {
                    line.push(' ');
                }
            }
            let trimmed = line.trim_end();
            out.push_str(trimmed);
            if r + 1 < rows {
                out.push('\r');
                out.push('\n');
            }
        }
        out
    }

    #[allow(dead_code)]
    pub fn cursor_position(&self) -> CursorPosition {
        let (row, col) = self.parser.screen().cursor_position();
        CursorPosition { row, col }
    }

    #[allow(dead_code)]
    pub fn window_title(&self) -> Option<String> {
        let title = self.parser.screen().title();
        if title.is_empty() {
            None
        } else {
            Some(title.to_string())
        }
    }
}

fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\x1b' && chars.next() == Some('[') {
            for c in chars.by_ref() {
                if c >= '\x40' && c <= '\x7E' {
                    break;
                }
            }
        } else if c != '\x1b' {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::AnsiParser;

    #[test]
    fn state_rehydrate_preserves_screen_modes_and_cursor_state() {
        let mut parser = AnsiParser::new(20, 5);
        parser.process(b"\x1b[?1049h\x1b[?1003h\x1b[?1006h\x1b[?1004h\x1b[?2004h\x1b[3;5Hhello");

        let state = parser.state_for_rehydrate();
        let state = String::from_utf8(state).expect("formatted vt100 state is UTF-8");

        assert!(state.contains("\x1b[?1049h"));
        assert!(state.contains("\x1b[?1003h"));
        assert!(state.contains("\x1b[?1006h"));
        assert!(state.contains("\x1b[?1004h"));
        assert!(state.contains("\x1b[?2004h"));
        assert!(state.contains("hello"));

        let mut replayed = vt100::Parser::new(5, 20, 1000);
        replayed.process(state.as_bytes());
        assert_eq!(replayed.screen().cursor_position(), (2, 9));
        assert_eq!(replayed.screen().cell(2, 4).unwrap().contents(), "h");

        let mut split = AnsiParser::new(20, 5);
        split.process(b"\x1b[?10");
        split.process(b"04h");
        assert!(String::from_utf8(split.state_for_rehydrate())
            .expect("formatted vt100 state is UTF-8")
            .contains("\x1b[?1004h"));
    }
}
